<?php

/**
 * @file
 * Module hooks for Search API Pinecone in Backdrop CMS.
 */

/**
 * Implements hook_autoload_info().
 */
function search_api_ai_pinecone_autoload_info() {
  return [
    'PineconeService'                 => 'includes/service.inc',
    'SearchApiAiPineconeVectorClient' => 'includes/SearchApiAiPineconeVectorClient.php',
  ];
}

/**
 * Implements hook_search_api_service_info().
 */
function search_api_ai_pinecone_search_api_service_info() {
  return [
    'pinecone' => [
      'name'        => t('Pinecone'),
      'description' => t('Pinecone backend for Search API AI.'),
      'class'       => 'PineconeService',
      'file'        => 'includes/service.inc',
    ],
  ];
}
